apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: aws-stack-template
  annotations:
    title: AWS Stack template
    description: Krateo Template Sample aws stack
    icon: fa-brands fa-aws
    owner: mauro.sala@kiratech.it
  labels:
    tags:
      - aws
      - eks
      - rds
      - stack
spec:
  widgets:
    - title: Name and description
      description: Name and description of the stack.
      properties:
        name:
          title: Name
          description: The name of the component
          required: true
        description:
          title: Description
          description: Help others understand what this deployment does.
          required: true
        namespace:
          title: Krateo namespace
          description: Krateo namespace for the stack.
          required: true
    - title: Kubernetes
      box: Kubernetes cluster name and network name.
      boxStyle: info
      properties:
        clusterName:
          title: Cluster Name
          description: The name of the cluster
          required: true
        networkName:
          title: Network name
          description: The VPC network to use
          required: true
        clusterNodes:
          title: Cluster Nodes
          description: The number of nodes in the cluster
          required: true
          type: number
          default: 3
        maxClusterNodes:
          title: Max Cluster Nodes
          description: The maximum number of nodes in the cluster
          required: true
          type: number
          default: 5

    - title: Database
      box: Please specify the database name, region, storage type, instance class and engine version.
      boxStyle: warning
      properties:
        rdsName:
          title: Rds Name
          description: The name of the RDS
          required: true
        rdsInstanceClass:
          title: Rds Instance Class
          description: The instance class of the RDS
          required: true
          default: db.t3.micro
          type: radio
          values:
            - title: db.t3.micro
              value: db.t3.micro
              description: 1 core\n2 vCPU\n1 GB of memory
            - title: db.t3.medium
              value: db.t3.medium
              description: 1 core\n2 vCPU\n2 GB of memory
            - title: db.t3.large
              value: db.t3.large
              description: 2 core\n2 vCPU\n8 GB of memory
        rdsEngine:
          title: Rds Engine
          description: The engine of the RDS
          required: true
          default: postgres
        rdsEngineVersion:
          title: Rds Engine Version
          description: The engine version of the RDS
          required: true
          default: 13.4
        rdsDataDiskSizeGb:
          title: Rds Disk Size
          description: The size of the RDS disk
          required: true
          default: 10
          type: number
        rdsRegion:
          title: Rds Region
          description: The region of the RDS
          required: true
          default: eu-central-1
        rdsStorageType:
          title: Rds Storage Type
          description: The storage type of the RDS
          required: true
          default: standard
          values:
            - standard
            - gp2
            - io1

    - title: Git repository destination
      box: Set the destination repository.
      properties:
        provider:
          title: Git Provider
          required: true
          default: github.com
          values:
            - github.com
        organizationName:
          title: Repository Organization
          required: true
          description: Organization name
          default: krateoplatformops
        repositoryName:
          title: Repository Name
          required: true
          description: The name of the repository
